version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      major:
        applies-to: version-updates
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      major:
        applies-to: version-updates
        update-types:
          - "major"