language: java
sudo: true
dist: trusty
before_install:
  - chmod +x gradlew
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
    - jdk: openjdk15
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea
script:
  - "travis_wait ./gradlew buildPlugin -s"